"""
Django settings for eyewear project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG')

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'auth.User'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'members',
    'django_daraja',
    'phonenumber_field',
    'cloudinary_storage',
    'cloudinary',


]
#phonenumber
PHONENUMBER_DEFAULT_REGION = 'KE'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eyewear.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eyewear.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

import dj_database_url

database_url = os.environ.get('DATABASE_URL')

DATABASES = {
  'default': dj_database_url.parse(database_url)
}


#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.sqlite3',
   #     'NAME': BASE_DIR / 'food.sqlite3',
    #}
#}
# DATABASES = {
#     'default': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': 'Food',
#     'USER':'postgres',
#     'PASSWORD':'9281',
#     'HOST':'127.0.0.1',
#     'PORT': '5433',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

'''#mpesa
MPESA_CONSUMER_KEY = 'amxJ81GpzpIFAMu1WiU9hR8wV2KsN2sWoRGcDdivLXjBq99f'
MPESA_CONSUMER_SECRET = '5DfevQUOAu6XKeOeCoGpEVfV52aGZNvwQyUlgIAzFSdtrAL5KHLdGJwyddw5eUZZ'
MPESA_ENVIRONMENT = 'sandbox'
MPESA_SHORTCODE = '600978'
#MPESA_EXPRESS_SHORTCODE = '174379'
MPESA_SHORTCODE_TYPE = 'till_number'
#MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"

#MPESA_CALLBACK_URL = 'your_callback_url''8055688'
#MPESA_SECURITY ="R5Ohdkzd7PkxdA1aFTm+cXkjT/nbMYDrSPFCA4st39zUnXx7PRFdzjQ5vgr2ZLN5ojObT60HPKdi2jNe0NE79Gq1ISngEDnxoXjYQow0xPU2OwKKTAoCyKQyqWtEg6JJI72qAXZtpVyfF/ucuMZCd8+dTjjIwT6vffOy/mxeXjUUEwvZsbiYv/jvIv42BUlBnky4r3n3UFMQvNwknVbMDIV1gM3qsGcJkzVSLsl6wE24MjGSvgeOorxZFtm0oyeny7H+wFAdVIcAXUd+VaSUOvQXIFAPk0aN7Osn+Q9AWwCkjq7eZU7HUDAG0CG8wCDkr1v2xYjKHAUO5/htHUg12A=="
'''
MPESA_CONSUMER_KEY = 'amxJ81GpzpIFAMu1WiU9hR8wV2KsN2sWoRGcDdivLXjBq99f'
MPESA_CONSUMER_SECRET = '5DfevQUOAu6XKeOeCoGpEVfV52aGZNvwQyUlgIAzFSdtrAL5KHLdGJwyddw5eUZZ'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_ENVIRONMENT = 'sandbox'
MPESA_SHORTCODE_TYPE = 'till_number'
MPESA_EXPRESS_SHORTCODE = '174379'
MPESA_SHORTCODE = '600978'

#MPESA_CALLBACK_URL = 'your_callback_url''8055688'
#MPESA_SECURITY ="R5Ohdkzd7PkxdA1aFTm+cXkjT/nbMYDrSPFCA4st39zUnXx7PRFdzjQ5vgr2ZLN5ojObT60HPKdi2jNe0NE79Gq1ISngEDnxoXjYQow0xPU2OwKKTAoCyKQyqWtEg6JJI72qAXZtpVyfF/ucuMZCd8+dTjjIwT6vffOy/mxeXjUUEwvZsbiYv/jvIv42BUlBnky4r3n3UFMQvNwknVbMDIV1gM3qsGcJkzVSLsl6wE24MjGSvgeOorxZFtm0oyeny7H+wFAdVIcAXUd+VaSUOvQXIFAPk0aN7Osn+Q9AWwCkjq7eZU7HUDAG0CG8wCDkr1v2xYjKHAUO5/htHUg12A=="


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = '/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'


CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUD_NAME'),
    'API_KEY': os.environ.get('API_KEY'),
    'API_SECRET':os.environ.get ('API_SECRET')
}
