# Generated by Django 4.1.5 on 2024-03-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
