# Generated by Django 4.1.5 on 2024-02-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_stock',
        ),
    ]
