# Generated by Django 4.1.5 on 2024-02-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_remove_products_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='target',
        ),
    ]
