# Generated by Django 4.1.5 on 2024-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_remove_products_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_orders',
            name='shipping_details',
            field=models.CharField(default='CBD,Amboseli 12', max_length=50),
        ),
    ]
