# Generated by Django 4.1.5 on 2024-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_alter_all_orders_shipping_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
